## Mezcla de 3 DF con la función merge

In [1]:
import pandas as pd

In [4]:
path = "../../practicas/avanzado2/pandas/merge/"

In [5]:
dfPed = pd.read_csv(path+"Pedidos.txt", sep=";")
dfPed.head()

   idpedido cliente  idempleado  idempresa  importe       pais
0     10248   WILMK           5          3    32.38  Finlandia
1     10249   TOMSP           6          1    11.61   Alemania
2     10250   HANAR           4          2    65.83     Brasil
3     10251   VICTE           3          1    41.34    Francia
4     10252   SUPRD           4          2    51.30    Belgica

In [6]:
dfEmpr = pd.read_csv(path+"Empresas.txt", sep=";")
dfEmpr.head()

   id           empresa
0   1    Speedy Express
1   2    United Package
2   3  Federal Shipping

In [7]:
dfEmpl = pd.read_csv(path+"Empleados.txt", sep=";")
dfEmpl.head()

   id     nombre                     cargo
0   1    Davolio   Representante de ventas
1   2     Fuller  Vicepresidente comercial
2   3  Leverling   Representante de ventas
3   4    Peacock   Representante de ventas
4   5   Buchanan         Gerente de ventas